### ISSUE TITLE
Add properties to server show command

### ISSUE THREAD

**Issue by briangustafson** [oracle/knife-oci#42]
Some fields that we might want to add are in bold below (looking at what's in the console is useful as well):

Display Name: instance20170731180604
Instance ID: ocid1.instance.oc1.iad.abuwcljt4bn5d4oksbqqfjmpnr36rlo2jm2wo7yqg7ov7zy4znmk56hvuabc
**Lifecycle State: RUNNING**
Availability Domain: IwGV:US-ASHBURN-AD-3
**Compartment Name: Chef Compartment**
Compartment ID: ocid1.compartment.oc1..aaaaaaaa6y3zzwkqlcyupl6msnblrhffavz6bu6phk7q265kfsil3ilekksq
Region: iad
**Image Name: Oracle-Linux-7.3-2017.07.17-0**
Image ID: ocid1.image.oc1.iad.aaaaaaaah2d5y4jlyi6q5mus4ihabunzdzuiwmuc3pequv27jfkc5eb4ylcq
Shape: VM.Standard1.2
**VCN Name: my_vcn
VCN ID: ocid1.vcn.oc1.iad.aaaaaaaa6crzmj5swotei3hp7lc2eq2d54dqwaphu3jsvjsanvia3h6nnabc**
**Launched: Mon, 24 Jul 2017 01:04:06 GMT**
Primary Public IP Address: 129.213.54.197
Primary Private IP Address: 10.0.2.13
Primary Hostname: instance20170731180604
**Primary FQDN: instance20160731180604.sub06221911123.chefvcn.oraclevcn.com
Primary Subnet Name: my_subnet**

**Comment by lidl** [comment]
I believe this issue can be closed with the merge of the refactored 'server show'
and 'server create' code that happened in pull request #44

**Comment by briangustafson** [comment]
Yep, closing
