### ISSUE TITLE
ERROR: TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by akashsarpate** [oracle/knife-oci#55]
I am trying to provision compute on oracle cloud using knife oci command and it is giving following error while bootstrap:
Waiting for instance to reach running state......................................done
Instance 'Chef8' is now running.
Private IP Address: XX.XX.XX.XX
Waiting for ssh access...done
Bootstrapping with node name 'Chef8'.
ERROR: TypeError: no implicit conversion of nil into String

my command for knife oci :
 
knife oci server create \
  --availability-domain 'muyX:US-ASHBURN-AD-1' \
  --compartment-id 'ocid1.compartment.oc1..abcd' \
  --image-id 'ocid1.image.oc1.iad.abacd' \
  --shape 'VM.Standard1.2' \
  --subnet-id 'ocid1.subnet.oc1.iad.abcd' \
  --ssh-authorized-keys-file publickey.pub \
  --display-name Chef8 \
  --identity-file private.pem \
  --region us-ashburn-1 \
  --node-name Chef8 \

**Comment by briangustafson** [comment]
Are you by any chance using a private Subnet? It appears that the instance does not have a public IP address, so I suspect that that is the issue. The knife-oci plugin currently requires the instance to have a public IP address, which in turn requires a public Subnet. Will that work for your scenario, and can you give that a try?

We are currently looking into support for instances without public IP addresses. In the meantime, there should definitely be a better error message than what you're seeing, and the documentation should make clearer that a public subnet is required.

Thanks for reporting this.

**Comment by akashsarpate** [comment]
Thanks for quick response.
Yes issue was due to private Ip, we can only private ip's configured in our environment.
I have made changes in oci_server_create.rb file and made bootstrap as private ip and it other places instead of public ip.
It resolved my issue.
