### ISSUE TITLE
Add support for new OCI storage type - File Systems (aka File Storage Service)

### ISSUE THREAD

**Issue by gcstang** [oracle/knife-oci#59]
Oracle [recently announced](https://blogs.oracle.com/cloud-infrastructure/introducing-oracle-cloud-infrastructure-file-storage-service) the public availability of Oracle Cloud Infrastructure File Storage Service (FSS) in all OCI regions. Here is the [File Storage Service API](https://docs.us-phoenix-1.oraclecloud.com/api/#/en/filestorage/20171215/).

**Comment by briangustafson** [comment]
Hi @gcstang - Could you elaborate on what functionality from the File Storage Service you would like to be available in knife-oci? Is there a specific use case that you have in mind?
